"use client";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Heart, MessageCircle, Bookmark } from "lucide-react";
import { useState } from "react";
import { RequireUserType } from "@/components/auth/require-user-type";
import { DashboardShell } from "@/components/dashboard/dashboard-shell";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { addPostComment, createPost, listFeed, listPostComments, togglePostLike, togglePostSave, uploadPostMedia, type PostVisibility, type SocialPost } from "@/lib/social-feed-api";

function PostCard({ post }: { post: SocialPost }) { const qc=useQueryClient(); const [comment,setComment]=useState(""); const [open,setOpen]=useState(false); const comments=useQuery({queryKey:["social-comments",post.id],queryFn:()=>listPostComments(post.id),enabled:open}); const add=useMutation({mutationFn:()=>addPostComment(post.id,comment),onSuccess:()=>{setComment("");qc.invalidateQueries({queryKey:["social-comments",post.id]});qc.invalidateQueries({queryKey:["social-feed"]})}}); const refresh=()=>qc.invalidateQueries({queryKey:["social-feed"]}); return <Card><CardContent className="space-y-3 pt-6"><header><p className="font-medium">{post.author.name}</p>{post.author.username&&<p className="text-xs text-muted-foreground">@{post.author.username}</p>}</header><p className="whitespace-pre-wrap text-sm">{post.body}</p>{post.media.map(m=><div key={m.id}>{m.media_type==="image"?<img src={m.url} alt="Post media" className="max-h-96 w-full rounded-lg object-cover"/>:m.media_type==="video"?<video src={m.url} controls className="max-h-96 w-full rounded-lg"/>:<audio src={m.url} controls className="w-full"/>}{m.processing_status!=="ready"&&<p className="text-xs text-muted-foreground">Media is {m.processing_status}.</p>}</div>)}<div className="flex gap-2"><Button size="sm" variant={post.liked_by_me?"default":"outline"} onClick={()=>togglePostLike(post.id).then(refresh)}><Heart className="size-4"/> {post.like_count}</Button><Button size="sm" variant="outline" onClick={()=>setOpen(!open)}><MessageCircle className="size-4"/> {post.comment_count}</Button><Button size="sm" variant={post.saved_by_me?"default":"outline"} onClick={()=>togglePostSave(post.id).then(refresh)}><Bookmark className="size-4"/></Button></div>{open&&<section className="space-y-2 border-t pt-3">{comments.data?.map(c=><p key={c.id} className="text-sm"><b>{c.author.name}: </b>{c.body}</p>)}<div className="flex gap-2"><Textarea value={comment} onChange={e=>setComment(e.target.value)} placeholder="Write a comment" className="min-h-10"/><Button disabled={!comment.trim()||add.isPending} onClick={()=>add.mutate()}>Reply</Button></div></section>}</CardContent></Card>; }
function Composer(){const qc=useQueryClient();const [body,setBody]=useState("");const [file,setFile]=useState<File|null>(null);const [visibility,setVisibility]=useState<PostVisibility>("public");const publish=useMutation({mutationFn:async()=>{const p=await createPost(body,visibility);if(file)await uploadPostMedia(p.id,file)},onSuccess:()=>{setBody("");setFile(null);qc.invalidateQueries({queryKey:["social-feed"]})}});return <Card><CardContent className="space-y-3 pt-6"><Textarea value={body} onChange={e=>setBody(e.target.value)} placeholder="Share something with the Clout community..."/><select className="h-9 rounded-md border bg-background px-3 text-sm" value={visibility} onChange={e=>setVisibility(e.target.value as PostVisibility)}><option value="public">Public</option><option value="followers">Followers only</option><option value="brands_only">Brands only</option><option value="private">Only me</option></select><input type="file" onChange={e=>setFile(e.target.files?.[0]??null)}/><Button disabled={!body.trim()||publish.isPending} onClick={()=>publish.mutate()}>Publish</Button></CardContent></Card>}
export default function SocialPage(){const feed=useQuery({queryKey:["social-feed"],queryFn:listFeed});return <RequireUserType allow={["brand","influencer"]}><DashboardShell title="Clout feed"><main className="mx-auto max-w-2xl space-y-4"><Composer/>{feed.data?.map(p=><PostCard key={p.id} post={p}/>)}</main></DashboardShell></RequireUserType>}
