import os
import shutil
import tempfile
import uuid
import mimetypes
from abc import ABC, abstractmethod
from functools import lru_cache

from fastapi import HTTPException, UploadFile, status

from app.core.config import get_settings

settings = get_settings()


class StorageBackend(ABC):
    """Every call site (upload handlers, FFmpeg service) talks to this interface only.
    Swapping `LocalStorageBackend` for an S3/MinIO-backed implementation later is a
    one-class change, not a rewrite — same contract the payments module uses for
    MoMo-vs-future-providers.
    """

    @abstractmethod
    def save(self, key: str, content: bytes) -> None: ...

    @abstractmethod
    def read(self, key: str) -> bytes: ...

    @abstractmethod
    def delete(self, key: str) -> None: ...

    @abstractmethod
    def local_path(self, key: str) -> str:
        """Absolute filesystem path FFmpeg can read/write. Only meaningful for
        backends that are actually local; an S3 backend would instead need to
        download to a temp path before invoking ffmpeg and upload the result after.
        """
        ...

    @abstractmethod
    def commit_local(self, key: str) -> None:
        """Persist a file generated at ``local_path(key)``.

        Local storage already writes directly to its final path. Remote object
        stores need this explicit hand-off after FFmpeg creates a rendition or
        thumbnail in the worker's temporary filesystem.
        """
        ...

    @abstractmethod
    def url_for(self, key: str) -> str: ...


class LocalStorageBackend(StorageBackend):
    def __init__(self, media_root: str):
        self.media_root = os.path.abspath(media_root)

    def _resolve(self, key: str) -> str:
        # `key` is always server-generated (see generate_storage_key) — never
        # built from client input — so this is a defense-in-depth check, not the
        # primary guard against path traversal.
        full_path = os.path.abspath(os.path.join(self.media_root, key))
        if not full_path.startswith(self.media_root + os.sep):
            raise ValueError("Invalid storage key")
        return full_path

    def save(self, key: str, content: bytes) -> None:
        full_path = self._resolve(key)
        os.makedirs(os.path.dirname(full_path), exist_ok=True)
        with open(full_path, "wb") as f:
            f.write(content)

    def read(self, key: str) -> bytes:
        with open(self._resolve(key), "rb") as f:
            return f.read()

    def delete(self, key: str) -> None:
        full_path = self._resolve(key)
        if os.path.exists(full_path):
            os.remove(full_path)

    def local_path(self, key: str) -> str:
        return self._resolve(key)

    def commit_local(self, key: str) -> None:
        # Files generated by FFmpeg are already in MEDIA_ROOT.
        self._resolve(key)

    def url_for(self, key: str) -> str:
        # Absolute, not relative: the frontend and this API are served from
        # different origins in production (Vercel vs. Render), so a bare
        # "/media/..." path would resolve against the frontend's own domain
        # and 404 instead of reaching this service.
        return f"{settings.PUBLIC_BASE_URL}/media/{key}"


class S3StorageBackend(StorageBackend):
    """Durable S3-compatible storage with a worker-local processing cache.

    R2 and MinIO speak the S3 API, so this avoids locking CLOUT to one cloud
    provider. Uploaded bytes go directly to the bucket; FFmpeg inputs and
    outputs use a short-lived local cache and outputs are uploaded explicitly
    through ``commit_local``.
    """

    def __init__(self) -> None:
        if not all((settings.S3_BUCKET, settings.S3_ACCESS_KEY_ID, settings.S3_SECRET_ACCESS_KEY)):
            raise RuntimeError("S3 storage requires S3_BUCKET, S3_ACCESS_KEY_ID, and S3_SECRET_ACCESS_KEY")
        try:
            import boto3
        except ImportError as exc:  # pragma: no cover - dependency is installed in deployment images
            raise RuntimeError("S3 storage requires the boto3 package") from exc
        self.bucket = settings.S3_BUCKET
        self.cache_root = os.path.join(tempfile.gettempdir(), "clout-storage")
        self.client = boto3.client(
            "s3",
            region_name=settings.S3_REGION,
            endpoint_url=settings.S3_ENDPOINT_URL,
            aws_access_key_id=settings.S3_ACCESS_KEY_ID,
            aws_secret_access_key=settings.S3_SECRET_ACCESS_KEY,
        )

    def _cache_path(self, key: str) -> str:
        normalized = key.replace("\\", "/").lstrip("/")
        if not normalized or ".." in normalized.split("/"):
            raise ValueError("Invalid storage key")
        path = os.path.abspath(os.path.join(self.cache_root, normalized))
        if not path.startswith(os.path.abspath(self.cache_root) + os.sep):
            raise ValueError("Invalid storage key")
        return path

    def save(self, key: str, content: bytes) -> None:
        self.client.put_object(
            Bucket=self.bucket,
            Key=key,
            Body=content,
            ContentType=mimetypes.guess_type(key)[0] or "application/octet-stream",
        )
        path = self._cache_path(key)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "wb") as file:
            file.write(content)

    def read(self, key: str) -> bytes:
        return self.client.get_object(Bucket=self.bucket, Key=key)["Body"].read()

    def delete(self, key: str) -> None:
        self.client.delete_object(Bucket=self.bucket, Key=key)
        path = self._cache_path(key)
        if os.path.exists(path):
            os.remove(path)

    def local_path(self, key: str) -> str:
        path = self._cache_path(key)
        if os.path.exists(path):
            return path
        os.makedirs(os.path.dirname(path), exist_ok=True)
        try:
            self.client.download_file(self.bucket, key, path)
        except Exception:
            # An output key does not exist until FFmpeg writes it. Inputs that
            # genuinely do not exist still fail safely in ffprobe/ffmpeg.
            if os.path.exists(path):
                os.remove(path)
        return path

    def commit_local(self, key: str) -> None:
        path = self._cache_path(key)
        if not os.path.isfile(path):
            raise FileNotFoundError(f"Generated media is missing: {key}")
        self.client.upload_file(
            path,
            self.bucket,
            key,
            ExtraArgs={"ContentType": mimetypes.guess_type(key)[0] or "application/octet-stream"},
        )

    def url_for(self, key: str) -> str:
        # Toolkit assets can be available only to selected/eligible creators.
        # A short-lived URL keeps that server-side authorization meaningful even
        # after the browser has received a playable media URL.
        return self.client.generate_presigned_url(
            "get_object",
            Params={"Bucket": self.bucket, "Key": key},
            ExpiresIn=settings.MEDIA_URL_EXPIRE_SECONDS,
        )

    def clear_cache(self) -> None:
        """Useful to a worker shutdown hook; retained for operational tooling."""
        shutil.rmtree(self.cache_root, ignore_errors=True)


@lru_cache
def get_storage_backend() -> StorageBackend:
    if settings.STORAGE_BACKEND.lower() == "s3":
        return S3StorageBackend()
    return LocalStorageBackend(settings.MEDIA_ROOT)


_ASSET_TYPE_EXTENSIONS = {
    "video": {".mp4", ".mov", ".webm", ".mkv"},
    "image": {".jpg", ".jpeg", ".png", ".webp"},
    # SVG is intentionally not accepted: it is executable markup, unsuitable
    # for media later rendered or downloaded by other CLOUT users.
    "logo": {".jpg", ".jpeg", ".png", ".webp"},
    "audio": {".mp3", ".wav", ".m4a", ".aac"},
    "voiceover": {".mp3", ".wav", ".m4a", ".aac"},
}


def allowed_extensions(asset_type: str) -> set[str]:
    return _ASSET_TYPE_EXTENSIONS.get(asset_type, set())


def generate_storage_key(advertisement_id: uuid.UUID, asset_type: str, original_filename: str) -> str:
    ext = os.path.splitext(original_filename)[1].lower()
    return f"advertisements/{advertisement_id}/{asset_type}/{uuid.uuid4()}{ext}"


def generate_rendition_key(asset_id: uuid.UUID, platform: str) -> str:
    return f"renditions/{asset_id}/{platform}.mp4"


async def read_with_limit(file: UploadFile, max_bytes: int) -> bytes:
    """Streams an upload in 1MB chunks rather than trusting the client-sent
    Content-Length, which can be absent or wrong (e.g. chunked transfer encoding).
    """
    chunks: list[bytes] = []
    total = 0
    while True:
        chunk = await file.read(1024 * 1024)
        if not chunk:
            break
        total += len(chunk)
        if total > max_bytes:
            raise HTTPException(
                status_code=status.HTTP_413_REQUEST_ENTITY_TOO_LARGE,
                detail=f"File exceeds the {max_bytes // (1024 * 1024)}MB limit for this upload",
            )
        chunks.append(chunk)
    return b"".join(chunks)


def validate_media_signature(*, media_type: str, content: bytes) -> None:
    """Validate actual file signatures after upload, rather than trusting a
    browser-controlled Content-Type or filename. SVG is intentionally excluded
    from public social media because it can carry active content.
    """
    signatures = {
        "image": (b"\xff\xd8\xff", b"\x89PNG\r\n\x1a\n", b"RIFF"),
        "audio": (b"ID3", b"\xff\xfb", b"\xff\xf3", b"RIFF", b"ftyp"),
        "video": (b"\x1aE\xdf\xa3",),
    }
    matched = any(content.startswith(signature) for signature in signatures[media_type])
    # MP4/M4A containers place ftyp at offset 4; RIFF is further constrained to
    # avoid accepting arbitrary bytes beginning with that marker.
    if media_type in {"video", "audio"} and len(content) >= 12 and content[4:8] == b"ftyp":
        matched = True
    if content.startswith(b"RIFF") and len(content) >= 12 and content[8:12] not in {b"WEBP", b"WAVE"}:
        matched = False
    if not matched:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="File contents do not match the declared media type")
