"""initial_schema

Revision ID: 59ef2ed7528a
Revises: 
Create Date: 2026-08-31 11:14:50.831532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59ef2ed7528a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertisement_templates',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advertisement_templates_code'), 'advertisement_templates', ['code'], unique=True)
    op.create_table('fee_configs',
    sa.Column('brand_fee_pct', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('influencer_fee_pct', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oauth_login_states',
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=128), nullable=False),
    sa.Column('user_type', sa.Enum('brand', 'influencer', 'admin', name='user_type'), nullable=True),
    sa.Column('redirect_uri', sa.String(length=512), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_login_states_state'), 'oauth_login_states', ['state'], unique=True)
    op.create_table('permissions',
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_table('profile_highlights',
    sa.Column('owner_type', sa.Enum('brand', 'influencer', name='profile_owner_type'), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('award', 'event', name='highlight_category'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subtitle', sa.String(length=255), nullable=True),
    sa.Column('occurred_on', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_highlights_owner_id'), 'profile_highlights', ['owner_id'], unique=False)
    op.create_index(op.f('ix_profile_highlights_owner_type'), 'profile_highlights', ['owner_type'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('user_type', sa.Enum('brand', 'influencer', 'admin', name='user_type'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('oauth_provider', sa.String(length=32), nullable=True),
    sa.Column('oauth_subject', sa.String(length=255), nullable=True),
    sa.Column('security_question', sa.String(length=255), nullable=True),
    sa.Column('security_answer_hash', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('oauth_provider', 'oauth_subject', name='uq_user_oauth_identity')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_table('view_rates',
    sa.Column('platform', sa.Enum('tiktok', 'instagram', 'facebook', 'youtube', name='social_platform'), nullable=False),
    sa.Column('rate_per_view', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform')
    )
    op.create_table('wallets',
    sa.Column('owner_type', sa.Enum('brand', 'influencer', 'platform', 'escrow', 'external', name='wallet_owner_type'), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('balance', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_type', 'owner_id', 'currency', name='uq_wallet_owner_currency')
    )
    op.create_index(op.f('ix_wallets_owner_id'), 'wallets', ['owner_id'], unique=False)
    op.create_table('announcements',
    sa.Column('author_admin_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('audience', sa.Enum('all', 'brands', 'influencers', name='announcement_audience'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_admin_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_table('brands',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=128), nullable=True),
    sa.Column('province', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('admin_sector', sa.String(length=128), nullable=True),
    sa.Column('admin_cell', sa.String(length=128), nullable=True),
    sa.Column('admin_village', sa.String(length=128), nullable=True),
    sa.Column('address_detail', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('legacy', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('visibility_settings', sa.JSON(), nullable=False),
    sa.Column('verification_status', sa.Enum('unverified', 'pending', 'approved', 'rejected', name='verification_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('purpose', sa.Enum('verify_email', 'reset_password', name='email_token_purpose'), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_tokens_token_hash'), 'email_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_email_tokens_user_id'), 'email_tokens', ['user_id'], unique=False)
    op.create_table('influencers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('province', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('admin_sector', sa.String(length=128), nullable=True),
    sa.Column('admin_cell', sa.String(length=128), nullable=True),
    sa.Column('admin_village', sa.String(length=128), nullable=True),
    sa.Column('address_detail', sa.String(length=255), nullable=True),
    sa.Column('sector', sa.String(length=128), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('legacy', sa.Text(), nullable=True),
    sa.Column('profile_picture_url', sa.String(length=512), nullable=True),
    sa.Column('visibility_settings', sa.JSON(), nullable=False),
    sa.Column('follower_tier', sa.Enum('nano', 'micro', 'mid', 'macro', name='follower_tier'), nullable=True),
    sa.Column('estimated_followers', sa.Integer(), nullable=True),
    sa.Column('completed_slots_count', sa.Integer(), nullable=False),
    sa.Column('failed_slots_count', sa.Integer(), nullable=False),
    sa.Column('verification_status', sa.Enum('unverified', 'pending', 'approved', 'rejected', name='verification_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_influencers_username'), 'influencers', ['username'], unique=True)
    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('new_brand_media', 'influencer_post_published', 'slot_claimed', 'payment_confirmed', 'asset_comment', 'social_follow', 'social_like', 'social_comment', name='notification_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=512), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('social_accounts',
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.Enum('tiktok', 'instagram', 'facebook', 'youtube', name='social_platform'), nullable=False),
    sa.Column('external_account_id', sa.String(length=128), nullable=False),
    sa.Column('handle', sa.String(length=255), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('active', 'expired', 'revoked', 'disconnected', name='social_account_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id', 'platform', name='uq_social_account_owner_platform')
    )
    op.create_index(op.f('ix_social_accounts_owner_user_id'), 'social_accounts', ['owner_user_id'], unique=False)
    op.create_table('social_oauth_states',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.Enum('tiktok', 'instagram', 'facebook', 'youtube', name='social_platform'), nullable=False),
    sa.Column('state', sa.String(length=128), nullable=False),
    sa.Column('code_verifier', sa.String(length=128), nullable=True),
    sa.Column('redirect_uri', sa.String(length=512), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_oauth_states_state'), 'social_oauth_states', ['state'], unique=True)
    op.create_index(op.f('ix_social_oauth_states_user_id'), 'social_oauth_states', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('debit_wallet_id', sa.Uuid(), nullable=False),
    sa.Column('credit_wallet_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('type', sa.Enum('funding', 'escrow_hold', 'escrow_release', 'payout', 'refund', 'fee', 'adjustment', name='transaction_type'), nullable=False),
    sa.Column('reference', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['credit_wallet_id'], ['wallets.id'], ),
    sa.ForeignKeyConstraint(['debit_wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_credit_wallet_id'), 'transactions', ['credit_wallet_id'], unique=False)
    op.create_index(op.f('ix_transactions_debit_wallet_id'), 'transactions', ['debit_wallet_id'], unique=False)
    op.create_index(op.f('ix_transactions_reference'), 'transactions', ['reference'], unique=True)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('advertisements',
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('draft', 'ready', 'archived', name='advertisement_status'), nullable=False),
    sa.Column('script_text', sa.Text(), nullable=True),
    sa.Column('cta_text', sa.String(length=255), nullable=True),
    sa.Column('hashtags', sa.JSON(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['advertisement_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advertisements_brand_id'), 'advertisements', ['brand_id'], unique=False)
    op.create_table('conversations',
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('influencer_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'influencer_id', name='uq_conversation_pair')
    )
    op.create_index(op.f('ix_conversations_brand_id'), 'conversations', ['brand_id'], unique=False)
    op.create_index(op.f('ix_conversations_influencer_id'), 'conversations', ['influencer_id'], unique=False)
    op.create_table('payouts',
    sa.Column('influencer_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('momo', 'mock', name='payment_provider'), nullable=False),
    sa.Column('provider_reference', sa.String(length=64), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('fee_pct', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('pending', 'successful', 'failed', name='payment_status'), nullable=False),
    sa.Column('raw_provider_payload', sa.JSON(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payouts_influencer_id'), 'payouts', ['influencer_id'], unique=False)
    op.create_index(op.f('ix_payouts_provider_reference'), 'payouts', ['provider_reference'], unique=True)
    op.create_table('advertisement_assets',
    sa.Column('advertisement_id', sa.Uuid(), nullable=False),
    sa.Column('asset_type', sa.Enum('video', 'image', 'logo', 'audio', 'voiceover', name='asset_type'), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('uploaded', 'processing', 'ready', 'failed', name='asset_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('moderation_status', sa.Enum('pending', 'approved', 'rejected', name='asset_moderation_status'), nullable=False),
    sa.Column('moderation_note', sa.Text(), nullable=True),
    sa.Column('moderated_by_admin_id', sa.Uuid(), nullable=True),
    sa.Column('moderated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['advertisement_id'], ['advertisements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['moderated_by_admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_advertisement_assets_advertisement_id'), 'advertisement_assets', ['advertisement_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('advertisement_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending_funding', 'funded', 'listed', 'active', 'completed', 'cancelled', name='campaign_status'), nullable=False),
    sa.Column('platforms', sa.JSON(), nullable=False),
    sa.Column('target_views', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Enum('nano', 'micro', 'mid', 'macro', name='follower_tier'), nullable=False),
    sa.Column('slot_count', sa.Integer(), nullable=False),
    sa.Column('performance_window_days', sa.Integer(), nullable=False),
    sa.Column('target_sector', sa.String(length=128), nullable=True),
    sa.Column('target_location', sa.String(length=128), nullable=True),
    sa.Column('rate_snapshot', sa.JSON(), nullable=False),
    sa.Column('brand_fee_pct', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('total_brand_payment', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['advertisement_id'], ['advertisements.id'], ),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_brand_id'), 'campaigns', ['brand_id'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('sender_user_id', sa.Uuid(), nullable=False),
    sa.Column('message_type', sa.Enum('text', 'audio', 'video', 'voice_note', 'document', name='message_type'), nullable=False),
    sa.Column('text_body', sa.Text(), nullable=True),
    sa.Column('attachment_key', sa.String(length=512), nullable=True),
    sa.Column('attachment_original_filename', sa.String(length=255), nullable=True),
    sa.Column('attachment_mime_type', sa.String(length=128), nullable=True),
    sa.Column('attachment_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_table('advertisement_renditions',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.Enum('tiktok', 'instagram', 'facebook', 'youtube', name='social_platform'), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'ready', 'failed', name='rendition_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['advertisement_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'platform', name='uq_rendition_asset_platform')
    )
    op.create_index(op.f('ix_advertisement_renditions_asset_id'), 'advertisement_renditions', ['asset_id'], unique=False)
    op.create_table('asset_comments',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('author_user_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['advertisement_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_comments_asset_id'), 'asset_comments', ['asset_id'], unique=False)
    op.create_table('asset_likes',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['advertisement_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'user_id', name='uq_asset_like_per_user')
    )
    op.create_index(op.f('ix_asset_likes_asset_id'), 'asset_likes', ['asset_id'], unique=False)
    op.create_table('campaign_reports',
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=False),
    sa.Column('data_snapshot', sa.JSON(), nullable=False),
    sa.Column('generator', sa.Enum('template', 'anthropic', name='report_generator_mode'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_reports_campaign_id'), 'campaign_reports', ['campaign_id'], unique=False)
    op.create_table('campaign_slots',
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.Enum('tiktok', 'instagram', 'facebook', 'youtube', name='social_platform'), nullable=False),
    sa.Column('tier', sa.Enum('nano', 'micro', 'mid', 'macro', name='follower_tier'), nullable=False),
    sa.Column('target_views', sa.Integer(), nullable=False),
    sa.Column('budget_allocated', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('status', sa.Enum('open', 'claimed', 'published', 'tracking', 'completed', 'partially_completed', 'failed', 'recovered', 'cancelled', name='slot_status'), nullable=False),
    sa.Column('influencer_id', sa.Uuid(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('recovered_from_slot_id', sa.Uuid(), nullable=True),
    sa.Column('recovery_generation', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], ),
    sa.ForeignKeyConstraint(['recovered_from_slot_id'], ['campaign_slots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_slots_campaign_id'), 'campaign_slots', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_slots_influencer_id'), 'campaign_slots', ['influencer_id'], unique=False)
    op.create_table('contracts',
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('influencer_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('terms_text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('proposed', 'accepted', 'declined', 'cancelled', name='contract_status'), nullable=False),
    sa.Column('proposed_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('responded_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposed_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_brand_id'), 'contracts', ['brand_id'], unique=False)
    op.create_index(op.f('ix_contracts_influencer_id'), 'contracts', ['influencer_id'], unique=False)
    op.create_table('payments',
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('momo', 'mock', name='payment_provider'), nullable=False),
    sa.Column('provider_reference', sa.String(length=64), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('pending', 'successful', 'failed', name='payment_status'), nullable=False),
    sa.Column('raw_provider_payload', sa.JSON(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_campaign_id'), 'payments', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_payments_provider_reference'), 'payments', ['provider_reference'], unique=True)
    op.create_table('refunds',
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('momo', 'mock', name='payment_provider'), nullable=False),
    sa.Column('provider_reference', sa.String(length=64), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('pending', 'successful', 'failed', name='payment_status'), nullable=False),
    sa.Column('raw_provider_payload', sa.JSON(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refunds_campaign_id'), 'refunds', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_refunds_provider_reference'), 'refunds', ['provider_reference'], unique=True)
    op.create_table('social_posts',
    sa.Column('campaign_slot_id', sa.Uuid(), nullable=False),
    sa.Column('social_account_id', sa.Uuid(), nullable=True),
    sa.Column('platform', sa.Enum('tiktok', 'instagram', 'facebook', 'youtube', name='social_platform'), nullable=False),
    sa.Column('publish_mode', sa.Enum('auto', 'manual', name='publish_mode'), nullable=False),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('external_post_id', sa.String(length=128), nullable=True),
    sa.Column('post_url', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.Enum('pending', 'published', 'failed', 'deleted', name='social_post_status'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_slot_id'], ['campaign_slots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['social_account_id'], ['social_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_posts_campaign_slot_id'), 'social_posts', ['campaign_slot_id'], unique=True)
    op.create_table('comments',
    sa.Column('social_post_id', sa.Uuid(), nullable=False),
    sa.Column('external_comment_id', sa.String(length=128), nullable=False),
    sa.Column('author_handle', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['social_post_id'], ['social_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('social_post_id', 'external_comment_id', name='uq_comment_post_external_id')
    )
    op.create_index(op.f('ix_comments_social_post_id'), 'comments', ['social_post_id'], unique=False)
    op.create_table('post_metric_snapshots',
    sa.Column('social_post_id', sa.Uuid(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['social_post_id'], ['social_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_metric_snapshots_social_post_id'), 'post_metric_snapshots', ['social_post_id'], unique=False)
    op.create_table('comment_analyses',
    sa.Column('comment_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('question', 'suggestion', 'complaint', 'positive', 'negative', 'neutral', 'other', name='comment_category'), nullable=False),
    sa.Column('sentiment_label', sa.Enum('positive', 'negative', 'neutral', name='sentiment_label'), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('classifier_version', sa.String(length=64), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_analyses_comment_id'), 'comment_analyses', ['comment_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_analyses_comment_id'), table_name='comment_analyses')
    op.drop_table('comment_analyses')
    op.drop_index(op.f('ix_post_metric_snapshots_social_post_id'), table_name='post_metric_snapshots')
    op.drop_table('post_metric_snapshots')
    op.drop_index(op.f('ix_comments_social_post_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_social_posts_campaign_slot_id'), table_name='social_posts')
    op.drop_table('social_posts')
    op.drop_index(op.f('ix_refunds_provider_reference'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_campaign_id'), table_name='refunds')
    op.drop_table('refunds')
    op.drop_index(op.f('ix_payments_provider_reference'), table_name='payments')
    op.drop_index(op.f('ix_payments_campaign_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_contracts_influencer_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_brand_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_campaign_slots_influencer_id'), table_name='campaign_slots')
    op.drop_index(op.f('ix_campaign_slots_campaign_id'), table_name='campaign_slots')
    op.drop_table('campaign_slots')
    op.drop_index(op.f('ix_campaign_reports_campaign_id'), table_name='campaign_reports')
    op.drop_table('campaign_reports')
    op.drop_index(op.f('ix_asset_likes_asset_id'), table_name='asset_likes')
    op.drop_table('asset_likes')
    op.drop_index(op.f('ix_asset_comments_asset_id'), table_name='asset_comments')
    op.drop_table('asset_comments')
    op.drop_index(op.f('ix_advertisement_renditions_asset_id'), table_name='advertisement_renditions')
    op.drop_table('advertisement_renditions')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_campaigns_brand_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_advertisement_assets_advertisement_id'), table_name='advertisement_assets')
    op.drop_table('advertisement_assets')
    op.drop_index(op.f('ix_payouts_provider_reference'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_influencer_id'), table_name='payouts')
    op.drop_table('payouts')
    op.drop_index(op.f('ix_conversations_influencer_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_brand_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_advertisements_brand_id'), table_name='advertisements')
    op.drop_table('advertisements')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_transactions_reference'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_debit_wallet_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_credit_wallet_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_social_oauth_states_user_id'), table_name='social_oauth_states')
    op.drop_index(op.f('ix_social_oauth_states_state'), table_name='social_oauth_states')
    op.drop_table('social_oauth_states')
    op.drop_index(op.f('ix_social_accounts_owner_user_id'), table_name='social_accounts')
    op.drop_table('social_accounts')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_influencers_username'), table_name='influencers')
    op.drop_table('influencers')
    op.drop_index(op.f('ix_email_tokens_user_id'), table_name='email_tokens')
    op.drop_index(op.f('ix_email_tokens_token_hash'), table_name='email_tokens')
    op.drop_table('email_tokens')
    op.drop_table('brands')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('announcements')
    op.drop_index(op.f('ix_wallets_owner_id'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_table('view_rates')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_profile_highlights_owner_type'), table_name='profile_highlights')
    op.drop_index(op.f('ix_profile_highlights_owner_id'), table_name='profile_highlights')
    op.drop_table('profile_highlights')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_oauth_login_states_state'), table_name='oauth_login_states')
    op.drop_table('oauth_login_states')
    op.drop_table('fee_configs')
    op.drop_index(op.f('ix_advertisement_templates_code'), table_name='advertisement_templates')
    op.drop_table('advertisement_templates')
    # ### end Alembic commands ###
