"""add_social_safety_controls

Revision ID: b1fe9e9ae443
Revises: d5ffd46e78b5
Create Date: 2026-08-31 12:20:48.745354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1fe9e9ae443'
down_revision: Union[str, None] = 'd5ffd46e78b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_blocks',
    sa.Column('blocker_id', sa.Uuid(), nullable=False),
    sa.Column('blocked_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['blocked_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocker_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('blocker_id', 'blocked_id'),
    sa.UniqueConstraint('blocker_id', 'blocked_id', name='uq_user_block')
    )
    op.create_table('native_post_reports',
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('reporter_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['native_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'reporter_id', name='uq_native_post_report')
    )
    op.create_index(op.f('ix_native_post_reports_post_id'), 'native_post_reports', ['post_id'], unique=False)
    op.create_index(op.f('ix_native_post_reports_reporter_id'), 'native_post_reports', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_native_post_reports_resolved'), 'native_post_reports', ['resolved'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_native_post_reports_resolved'), table_name='native_post_reports')
    op.drop_index(op.f('ix_native_post_reports_reporter_id'), table_name='native_post_reports')
    op.drop_index(op.f('ix_native_post_reports_post_id'), table_name='native_post_reports')
    op.drop_table('native_post_reports')
    op.drop_table('user_blocks')
    # ### end Alembic commands ###
