"""add_native_video_processing_lifecycle

Revision ID: d40a4d817e71
Revises: f639fbe3a245
Create Date: 2026-08-31 12:44:40.918044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd40a4d817e71'
down_revision: Union[str, None] = 'f639fbe3a245'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('native_post_media', sa.Column('processing_status', sa.String(length=16), server_default='ready', nullable=False))
    op.add_column('native_post_media', sa.Column('processed_storage_key', sa.String(length=512), nullable=True))
    op.add_column('native_post_media', sa.Column('thumbnail_storage_key', sa.String(length=512), nullable=True))
    op.add_column('native_post_media', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('native_post_media', sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False))
    op.create_index(op.f('ix_native_post_media_processing_status'), 'native_post_media', ['processing_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_native_post_media_processing_status'), table_name='native_post_media')
    op.drop_column('native_post_media', 'retry_count')
    op.drop_column('native_post_media', 'error_message')
    op.drop_column('native_post_media', 'thumbnail_storage_key')
    op.drop_column('native_post_media', 'processed_storage_key')
    op.drop_column('native_post_media', 'processing_status')
    # ### end Alembic commands ###
