"""add_social_reposts_and_hashtags

Revision ID: f639fbe3a245
Revises: b1fe9e9ae443
Create Date: 2026-08-31 12:29:54.744495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f639fbe3a245'
down_revision: Union[str, None] = 'b1fe9e9ae443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hashtags',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hashtags_name'), 'hashtags', ['name'], unique=True)
    op.create_table('native_post_hashtags',
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('hashtag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['hashtag_id'], ['hashtags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['native_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'hashtag_id')
    )
    with op.batch_alter_table('native_posts') as batch_op:
        batch_op.add_column(sa.Column('repost_of_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_native_posts_repost_of_id'), ['repost_of_id'], unique=False)
        batch_op.create_foreign_key('fk_native_posts_repost_of_id', 'native_posts', ['repost_of_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('native_posts') as batch_op:
        batch_op.drop_constraint('fk_native_posts_repost_of_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_native_posts_repost_of_id'))
        batch_op.drop_column('repost_of_id')
    op.drop_table('native_post_hashtags')
    op.drop_index(op.f('ix_hashtags_name'), table_name='hashtags')
    op.drop_table('hashtags')
    # ### end Alembic commands ###
